"""User-facing strings for the opt-in AI commands, kept in one place for the i18n seam.

docs/I18N.md declares console prose as localizable content and issue #39 tracks the gettext
entry point. Until that seam exists, every string the ``ai`` commands show a person lives
here so it can be wrapped in one pass, and none of it may imply that an advisory result is
a legal determination.
"""

from __future__ import annotations

DATA_FLOW_NOTICE = (
    "This command sends document text from the package to the configured model provider "
    "({provider}, model {model}). The provider's processing terms apply to that text. "
    "Nothing is written to a log. The default `check` command does not do this."
)
EXTRACTION_HEADER = "CEQA Preflight AI extraction draft"
EXTRACTION_SUMMARY = (
    "Summary: {found} field(s) found with a verified quote, {unknown} unknown (not stated or "
    "not extracted), {unverified} withheld because the quote did not verify."
)
DOCUMENT_LINE = "Document: {path} — {kind}{detail}"
NOT_ATTEMPTED = " — not extracted: {reason}"
MODEL_ERROR = " — model error: {error}"
FIELD_FOUND = '  [FOUND] {name}: {value}  (page {page}, quote: "{quote}")'
FIELD_UNKNOWN = "  [UNKNOWN] {name}: not stated in the text"
FIELD_UNVERIFIED = "  [WITHHELD] {name}: the model proposed a value but {note}"
DRAFT_MANIFEST_WRITTEN = "Wrote a DRAFT manifest to {path}. Review every value before using it."
DRAFT_MANIFEST_NONE = "No draft manifest: the package contains no PDF to draw from."
DRAFT_MANIFEST_FAILED_CLOSED = (
    "No draft manifest was written: at least one model call failed, and a draft built "
    "around a failure would present the gap as a result. Fix the provider error and re-run."
)
NEXT_STEP = (
    "Next: review the draft, correct it, then run `ceqa-preflight check {package} "
    "--filing-type {filing_type} --manifest {manifest}`. Only that check produces findings."
)
MANIFEST_COMMENT = (
    "# DRAFT manifest generated by `ceqa-preflight ai extract` ({provider}/{model}, "
    "prompt {prompt_version}, {generated_at}).\n"
    "# Every value below was copied from the document text and verified against a quote,\n"
    "# or left at a placeholder. Review and correct it before running `check --manifest`.\n"
    "# This is not a finding and not a determination of anything.\n"
)
