"""User-facing strings for the opt-in AI commands, kept in one place for the i18n seam.

docs/I18N.md declares console prose as localizable content and issue #39 tracks the gettext
entry point. Every string the ``ai`` commands show a person lives here so it can be wrapped
in one pass, and none of it may imply that an advisory result is a legal determination.

Each string is a function, not a constant: gettext's static extractor (``pybabel extract``,
``xgettext``) only finds ``_("literal text")`` calls whose argument is a string literal at
the call site, so the literal msgid has to live in the ``_()`` call itself, here, and
``ai/cli.py`` calls these functions instead of formatting a module-level constant. The
translation also has to happen when the function runs, under whatever locale is active at
that moment, not once at import time.
"""

from __future__ import annotations

from ceqa_preflight.i18n import _


def DATA_FLOW_NOTICE(*, provider: str, model: str) -> str:
    return _(
        "This command sends document text from the package to the configured model provider "
        "({provider}, model {model}). The provider's processing terms apply to that text. "
        "Nothing is written to a log. The default `check` command does not do this."
    ).format(provider=provider, model=model)


def EXTRACTION_HEADER() -> str:
    return _("CEQA Preflight AI extraction draft")


def EXTRACTION_SUMMARY(*, found: int, unknown: int, unverified: int) -> str:
    return _(
        "Summary: {found} field(s) found with a verified quote, {unknown} unknown (not stated "
        "or not extracted), {unverified} withheld because the quote did not verify."
    ).format(found=found, unknown=unknown, unverified=unverified)


def DOCUMENT_LINE(*, path: str, kind: str, detail: str) -> str:
    return _("Document: {path} — {kind}{detail}").format(path=path, kind=kind, detail=detail)


def NOT_ATTEMPTED(*, reason: object) -> str:
    return _(" — not extracted: {reason}").format(reason=reason)


def MODEL_ERROR(*, error: str) -> str:
    return _(" — model error: {error}").format(error=error)


def FIELD_FOUND(*, name: str, value: object, page: object, quote: object) -> str:
    return _('  [FOUND] {name}: {value}  (page {page}, quote: "{quote}")').format(
        name=name, value=value, page=page, quote=quote
    )


def FIELD_UNKNOWN(*, name: str) -> str:
    return _("  [UNKNOWN] {name}: not stated in the text").format(name=name)


def FIELD_UNVERIFIED(*, name: str, note: object) -> str:
    return _("  [WITHHELD] {name}: the model proposed a value but {note}").format(
        name=name, note=note
    )


def DRAFT_MANIFEST_WRITTEN(*, path: object) -> str:
    return _("Wrote a DRAFT manifest to {path}. Review every value before using it.").format(
        path=path
    )


def DRAFT_MANIFEST_NONE() -> str:
    return _("No draft manifest: the package contains no PDF to draw from.")


def DRAFT_MANIFEST_FAILED_CLOSED() -> str:
    return _(
        "No draft manifest was written: at least one model call failed, and a draft built "
        "around a failure would present the gap as a result. Fix the provider error and re-run."
    )


def NEXT_STEP(*, package: object, filing_type: str, manifest: object) -> str:
    return _(
        "Next: review the draft, correct it, then run `ceqa-preflight check {package} "
        "--filing-type {filing_type} --manifest {manifest}`. Only that check produces findings."
    ).format(package=package, filing_type=filing_type, manifest=manifest)


def MANIFEST_COMMENT(*, provider: str, model: str, prompt_version: str, generated_at: str) -> str:
    return _(
        "# DRAFT manifest generated by `ceqa-preflight ai extract` ({provider}/{model}, "
        "prompt {prompt_version}, {generated_at}).\n"
        "# Every value below was copied from the document text and verified against a quote,\n"
        "# or left at a placeholder. Review and correct it before running `check --manifest`.\n"
        "# This is not a finding and not a determination of anything.\n"
    ).format(
        provider=provider, model=model, prompt_version=prompt_version, generated_at=generated_at
    )


def EXPLANATION_HEADER(mode: str) -> str:
    if mode == "explain":
        return _("CEQA Preflight AI explanations")
    return _("CEQA Preflight AI correction drafts")


def EXPLANATION_SUMMARY(
    *, findings: int, claims_shown: int, claims_withheld: int, model_errors: int
) -> str:
    return _(
        "Summary: {findings} finding(s) covered, {claims_shown} claim(s) shown with verified "
        "quotes, {claims_withheld} claim(s) withheld (unverified or determination language), "
        "{model_errors} model error(s)."
    ).format(
        findings=findings,
        claims_shown=claims_shown,
        claims_withheld=claims_withheld,
        model_errors=model_errors,
    )


def EXPLANATION_NONE() -> str:
    return _("No failure, warning, or manual-review finding to cover.")


def FINDING_HEADER(*, rule_id: str, status: str, title: str, location: str) -> str:
    return _("{rule_id} [{status}] {title}{location}").format(
        rule_id=rule_id, status=status, title=title, location=location
    )


def FINDING_MESSAGE(*, message: str) -> str:
    return _("  Finding: {message}").format(message=message)


def CLAIM_LINE(*, index: int, text: str) -> str:
    return _("  {index}. {text}").format(index=index, text=text)


def CITATION_LINE(*, passage_id: str, quote: str) -> str:
    return _('     [{passage_id}] "{quote}"').format(passage_id=passage_id, quote=quote)


def SOURCE_LINE(*, title: str, kind: str, url: str, headings: str) -> str:
    return _("  Source: {title} ({kind}) — {url}{headings}").format(
        title=title, kind=kind, url=url, headings=headings
    )


def WITHHELD_LINE(*, count: int, reasons: str) -> str:
    return _("  Withheld: {count} claim(s) did not pass verification ({reasons}).").format(
        count=count, reasons=reasons
    )


def NOTE_LINE(*, note: str) -> str:
    return _("  Note: {note}").format(note=note)


def MODEL_ERROR_LINE(*, error: str) -> str:
    return _("  Model error: {error}").format(error=error)


def ASK_HEADER() -> str:
    return _("CEQA Preflight AI answer")


def ASK_QUESTION(*, question: str) -> str:
    return _("Question: {question}").format(question=question)


def REFUSAL(*, category: object, findings: str) -> str:
    return _(
        "CEQA Preflight does not determine legal sufficiency, predict whether a filing will be "
        "accepted, judge whether an exemption or determination is valid, or assess an agency's "
        "compliance. This question asks for that ({category}), so it is not answered here, in "
        "any wording.\n\nWhat this tool can tell you is the objective, technical findings in the "
        "report:\n{findings}\n\nFor whether the filing is sufficient, compliant, or will be "
        "accepted, consult a qualified CEQA reviewer or counsel."
    ).format(category=category, findings=findings)


def REFUSAL_NO_FINDINGS() -> str:
    return _("  (no failure, warning, or manual-review findings in this report)")


def ASK_NOTHING() -> str:
    return _("No claim passed verification, so nothing is shown.")
